from app.services.pipeline import LogXPipeline


FORTIGATE_LOG = (
    'date=2026-09-19 '
    'time=18:30:00 '
    'devname="FGT-01" '
    'devid="FG123" '
    'logid="0000000013" '
    'type="traffic" '
    'subtype="forward" '
    'srcip=10.0.0.5 '
    'srcport=51542 '
    'dstip=8.8.8.8 '
    'dstport=443 '
    'proto=6 '
    'sentbyte=1024 '
    'action="deny" '
    'policyid=10'
)


def test_full_fortigate_pipeline():

    pipeline = LogXPipeline()

    result = pipeline.process(
        FORTIGATE_LOG
    )

    assert result["status"] == "processed"

    assert result["raw"]["sha256"]

    assert result["raw"]["format"] == "key_value"

    assert result["parser"]["id"] == (
        "fortigate.traffic"
    )

    assert result["event"]["action"] == "deny"

    assert result["source"]["ip"] == (
        "10.0.0.5"
    )

    assert result["destination"]["ip"] == (
        "8.8.8.8"
    )

    assert result["destination"]["port"] == 443


def test_unknown_event_is_quarantined():

    pipeline = LogXPipeline()

    raw = (
        "completely unknown telemetry "
        "generated by mystery device"
    )

    result = pipeline.process(raw)

    assert result["status"] == "quarantined"

    assert result["parser"] is None

    assert result["raw"]["sha256"]