from app.services.source_detector import SourceDetector


detector = SourceDetector()


def test_detect_fortigate():

    raw = (
        'date=2026-09-19 time=18:30:00 '
        'devname="FGT-01" devid="FG123" '
        'logid="0000000013" type="traffic" '
        'subtype="forward" srcip=10.0.0.5 '
        'dstip=8.8.8.8 action="deny" '
        'policyid=10'
    )

    result = detector.detect(raw, "key_value")

    assert result["source"] == "fortigate"
    assert result["vendor"] == "Fortinet"
    assert result["confidence"] > 0.9


def test_detect_cisco_asa():

    raw = (
        "%ASA-6-302013: Built outbound TCP "
        "connection 123 for outside"
    )

    result = detector.detect(raw, "syslog")

    assert result["source"] == "cisco_asa"


def test_detect_palo_alto():

    raw = (
        "receive_time=2026-09-19 "
        "serial=0123456789 "
        "rule=allow-web "
        "sessionid=12345"
    )

    result = detector.detect(raw, "key_value")

    assert result["source"] == "palo_alto"


def test_detect_suricata():

    raw = """{
        "event_type": "alert",
        "src_ip": "10.0.0.5",
        "dest_ip": "8.8.8.8",
        "flow_id": 123,
        "alert": {
            "signature": "Test attack"
        }
    }"""

    result = detector.detect(raw, "json")

    assert result["source"] == "suricata"


def test_detect_zeek():

    raw = (
        "ts=1726741800.123 "
        "uid=Cabc123 "
        "id.orig_h=10.0.0.5 "
        "id.resp_h=8.8.8.8 "
        "id.orig_p=51542 "
        "id.resp_p=443"
    )

    result = detector.detect(raw, "key_value")

    assert result["source"] == "zeek"


def test_unknown_source():

    raw = (
        "completely unknown telemetry "
        "message generated by unknown system"
    )

    result = detector.detect(raw, "unknown")

    assert result["source"] == "unknown"
    assert result["confidence"] == 0.0